### PR TITLE
Addition and fixes of components/physics

### LINKED ISSUE #124: Add box component in physics

### PR DESCRIPTION
**Pull request by murex971**
Fixes #124

### CODE REVIEW

File: rootex/framework/components/physics/box_component.cpp [hunk 1]
```diff
@@ -0,0 +1,40 @@
+#include "box_component.h"
+
+BoxComponent::BoxComponent(Vector3 dimensions, const String& matName)
```
Comment (IronicallySerious) [inline rootex/framework/components/physics/box_component.cpp:3]: `const Vector3& dimensions`

File: rootex/framework/components/physics/box_component.cpp [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+	}
+}
+
+JSON::json BoxComponent::getJSON() const
+{
+	JSON::json j;
+
+	j["dimensions"]["x"] = m_Dimensions.x;
+	j["dimensions"]["y"] = m_Dimensions.y;
+	j["dimension.z"]["z"] = m_Dimensions.z;
```
Comment (IronicallySerious) [inline rootex/framework/components/physics/box_component.cpp:19]: `dimension.z` is not our standard way of saving stuff

File: rootex/framework/components/physics/box_component.cpp [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+	j["matName"] = m_MaterialName;
+
+	return j;
+}
+
+Component* BoxComponent::Create(const JSON::json& boxComponentData)
+{
+	BoxComponent* component = new BoxComponent(
+		{ boxComponentData["dimensions"]["x"], boxComponentData["dimensions"]["y"], boxComponentData["dimensions"]["z"] },
```
Comment (IronicallySerious) [inline rootex/framework/components/physics/box_component.cpp:29]: Here you've used `"dimensions"` but in getJSON() you used `"dimensions.z"`. This will not load the BoxComponent properly from the JSON file

File: rootex/framework/components/physics/box_component.h [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+
+	friend class EntityFactory;
+
+public:
+	BoxComponent(Vector3 dimensions, const String& matName);
+
+	Vector3 getDimensions() const { return m_Dimensions; }
+
+	virtual String getName() const override { return "BoxComponent"; };
+	virtual JSON::json getJSON() const override;
```
Comment (IronicallySerious) [inline rootex/framework/components/physics/box_component.h:22]: Add a draw() function as in all the other components. We want the ability to change the data inside this component from the editor. The overridable `Component::draw()` is meant for that
