### PR TITLE
fix extra prerender binds and change view, projection bind location

### LINKED ISSUE #152: every object is "bound" 4 times for 1 draw call
render_system.cpp-
```cpp
#ifdef ROOTEX_EDITOR
	renderPassRender(rootVC.get(), RenderPassEditor);
#endif // ROOTEX_EDITOR
	renderPassRender(rootVC.get(), RenderPassMain);
	{
		SkyBoxHelper skyHelper;
		renderPassRender(rootVC.get(), RenderPassSky);
	}
	{
		RenderingDevice::GetSingleton()->beginDrawUI();
		renderPassRender(rootVC.get(), RenderPassUI);
		RenderingDevice::GetSingleton()->endDrawUI();
	}
```
This causes the rendering logic to run 4 times on every object for a single Draw() call

### PR DESCRIPTION
**Pull request by sin3point14**
+ some cleanup
closes #152

### CODE REVIEW

File: rootex/framework/components/visual/model_visual_component.cpp [hunk 1]
```diff
@@ -97,18 +92,19 @@ void ModelVisualComponent::render(RenderPass renderPass)
 {
 	if (renderPass & m_RenderPass)
 	{
+		PSSolidConstantBuffer Cb = { m_Color };
+		reinterpret_cast<ColorMaterial*>(m_Material.get())->setPixelShaderConstantBuffer(Cb); //change
+
+		m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::Model, RenderSystem::GetSingleton()->getTopMatrix());
+		m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::View, RenderSystem::GetSingleton()->getCamera()->getView());
+		m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::Projection, RenderSystem::GetSingleton()->getCamera()->getProjection());
```
Comment (IronicallySerious) [inline rootex/framework/components/visual/model_visual_component.cpp:100]: Move this into ColorMaterial::bind()

File: rootex/framework/components/visual/textured_model_visual_component.cpp [hunk 2]
```diff
@@ -47,31 +47,22 @@ TexturedModelVisualComponent::~TexturedModelVisualComponent()
...
-		RenderSystem::GetSingleton()->pushMatrix(Matrix::Identity);
-		m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::Model, RenderSystem::GetSingleton()->getTopMatrix());
-		m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::ModelInverse, RenderSystem::GetSingleton()->getTopMatrix().Invert());
-	}
-
-	return true;
+	m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::Model, RenderSystem::GetSingleton()->getTopMatrix());
+	m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::ModelInverse, RenderSystem::GetSingleton()->getTopMatrix().Invert());
+	m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::View, RenderSystem::GetSingleton()->getCamera()->getView());
+	m_Material->setVertexShaderConstantBuffer(Material::VertexConstantBufferType::Projection, RenderSystem::GetSingleton()->getCamera()->getProjection());
```
Comment (IronicallySerious) [inline rootex/framework/components/visual/textured_model_visual_component.cpp:55]: Move this into TexturedMaterial::bind()

**Comment by IronicallySerious** [comment]
Changes should be done in #158
